# -*- coding: utf-8 -*-
"""FINAL builder for Quiz_02_Risk_Assessment.json (Week 02 Cyber, 30 Q).

Why this exists instead of relying on quiz_balancer --strict:
  `--strict` in this repo SHUFFLES the option arrays but does NOT recompute
  `correct`/`answer`, so after it runs the marked letter no longer points at
  the semantically correct option (verified: 14/30 desynced on 2026-09-26).
  It also shuffles `options_ar` independently of `options_en`.

This builder is the single source of truth:
  * writes schema v2,
  * rotates the three option lists TOGETHER (EN / AR / canonical stay in lockstep),
  * computes `correct`/`answer` from the rotation, so the key always matches
    the intended content,
  * lands the 30 keys on a balanced 8/8/7/7 pattern,
  * contains zero English parentheticals (strict-gate rule),
  * passes `--schema --check` (exit 0) on its own.

The strict gate is then run on a THROWAWAY COPY, purely as a balance report.
"""
import json, os, re
from collections import Counter

OUT = os.path.abspath(os.path.join(
    os.path.dirname(os.path.abspath(__file__)),
    "..", "..", "01_Semester_1", "01_Cyber_Security",
    "07_Quizzes_&_Anki", "Quiz_02_Risk_Assessment.json",
))
LETTERS = "ABCD"

# (id, concept_id, bloom, Q_en, Q_ar, [EN options], [AR options], correct_index_in_these_lists, explanation_ar)
ITEMS = [
("q1","risk_technical_definition","Remember",
 "How is the term 'risk' defined in its technical sense in the chapter?",
 "كيف يُعرَّف مصطلح 'الخطر' بمعناه التقني في الفصل؟",
 ["The quantitative probability that an error situation occurs and gives rise to damage.",
  "A subjective feeling of unease about possible future harm in an organisation.",
  "The total number of vulnerabilities remaining in an organisation's own IT system.",
  "The likelihood that a countermeasure fails when it is tested under real conditions."],
 ["الاحتمال الكمّي أن تحدث حالة خطأ وتؤدي إلى ضرر بحسب التعريف التقني للخطر.",
  "شعور ذاتي بعدم الارتياح تجاه ضرر محتمل مستقبلاً في المؤسسة العاملة بمجالها.",
  "العدد الكلي للثغرات المتبقية في النظام المعلوماتي الخاص بالمؤسسة نفسها.",
  "احتمال فشل الإجراء المضاد عند اختباره في ظروف التشغيل الحقيقية للأنظمة."],
 0,
 "التعريف التقني = الاحتمال الكمّي (quantitative probability) لحدوث حالة خطأ تؤدي إلى ضرر. الخيار الثاني يصف الخطر الذاتي (subjective)، والثالث والرابع ليسا التعريف."),

("q2","damage_breach_policy","Understand",
 "In IT security, with what is the word 'damage' synonymous?",
 "في أمن تقنية المعلومات، مع أي شيء يكون مصطلح 'الضرر' مرادفاً؟",
 ["A breach of the security policy that the organisation has defined for itself.",
  "A financial loss greater than the annual budget that was approved for it.",
  "A failure of the hardware components that support the organisation's systems.",
  "An outage that lasts longer than the declared recovery time objective."],
 ["خرق سياسة الأمن التي حدّدتها المؤسسة لنفسها في وثائقها الرسمية المعتمدة.",
  "خسارة مالية تتجاوز الموازنة السنوية التي اعتُمدت لذلك الغرض تحديداً فيها.",
  "فشل المكوّنات المادية التي تسند أنظمة المؤسسة في بيئة التشغيل الفعلية لها.",
  "انقطاع يستمر مدة أطول من هدف زمن الاستعادة المعلَن في خطة الاستمرارية."],
 0,
 "الضرر في أمن تقنية المعلومات مرادف لخرق سياسة الأمن (breach of the security policy) كما ينصّ الفصل صراحةً. البقية أنواع أخرى من الخسارة وليست المرادف."),

("q3","objective_vs_subjective_risk","Understand",
 "What distinguishes subjective risk from the objective definition of risk?",
 "ما الذي يميّز الخطر الذاتي (subjective) عن التعريف الموضوعي للخطر؟",
 ["It takes human factors such as public attitudes, trust and personality into account.",
  "It measures the frequency of attacks over a longer period than objective risk does.",
  "It applies only to the threats that are caused by mistakes made by inside users.",
  "It is calculated from the number of countermeasures rather than their effect."],
 ["يأخذ العوامل البشرية مثل مواقف الناس والثقة والشخصية في الحسبان عند التقييم.",
  "يقيس تكرار الهجمات على مدى زمني أطول ممّا يقيسه الخطر الموضوعي في العادة.",
  "يُطبَّق فقط على التهديدات الناتجة عن الأخطاء التي يرتكبها المستخدمون الداخليون.",
  "يُحسَب انطلاقاً من عدد الإجراءات المضادة بدل فعاليتها في تخفيض الخطر الكلي."],
 0,
 "الخطر الذاتي = الموقف كما يراه الناس، ويدخل فيه العامل البشري (المواقف، الثقة، الشخصية). الخطر الموضوعي كمّي قابل للقياس ولا يدخل فيه العامل البشري."),

("q4","threat_vulnerability_damage_chain","Apply",
 "In the shark-cage illustration, what does the welding fault in the cage represent?",
 "في تشبيه قفص القرش، ماذا يُمثّل عيب اللحام في القفص؟",
 ["The vulnerability, because it is the weakness that can be exploited to cause damage.",
  "The threat itself, because it is the danger that the swimmer is exposed to directly.",
  "The countermeasure, because it is the part that has degraded and needs to be repaired.",
  "The residual risk, because it remains after every possible control has been applied."],
 ["الثغرة، لأنه نقطة الضعف التي يمكن استغلالها لإحداث الضرر بالنظام في المثال.",
  "التهديد نفسه، لأنه الخطر الذي يتعرض له السبّاح بشكل مباشر داخل الماء في المثال.",
  "الإجراء المضاد، لأنه الجزء الذي تدهور ويحتاج إلى إصلاح واستبدال في المثال.",
  "الخطر المتبقي، لأنه يبقى بعد تطبيق كل الإجراءات المضادة الممكنة في المثال."],
 0,
 "سلسلة الضرر: threat (القرش) → vulnerability (عيب اللحام) → damage. عيب اللحام هو نقطة الضعف القابلة للاستغلال، أي الثغرة، ولا يُخلط مع التهديد."),

("q5","basic_risk_equation","Remember",
 "Which formula expresses the basic risk S of a threat?",
 "أي صيغة تعبّر عن الخطر الأساسي S لتهديد معيّن؟",
 ["S = F x K, where F is frequency and K is consequences of a successful attempt.",
  "S = F / K, where F is frequency and K is consequences of a successful attempt.",
  "S = F + K, where F is frequency and K is consequences of a successful attempt.",
  "S = F - K, where F is frequency and K is consequences of a successful attempt."],
 ["S = F × K، حيث F التكرار و K عواقب المحاولة الناجحة في المعادلة الأساسية.",
  "S = F / K، حيث F التكرار و K عواقب المحاولة الناجحة في المعادلة الأساسية.",
  "S = F + K، حيث F التكرار و K عواقب المحاولة الناجحة في المعادلة الأساسية.",
  "S = F − K، حيث F التكرار و K عواقب المحاولة الناجحة في المعادلة الأساسية."],
 0,
 "الخطر الأساسي S = F × K: F تكرار محاولات استغلال الثغرة، K عواقب المحاولة الناجحة. الضرب مطلوب لا الجمع، لأن كلا العاملين يجب أن يؤثر."),

("q6","residual_risk_equation","Remember",
 "Which formula expresses the residual risk R after countermeasures are introduced?",
 "أي صيغة تعبّر عن الخطر المتبقي R بعد إدخال الإجراءات المضادة؟",
 ["R = S x M, where S is the risk and M is the level of countermeasures applied.",
  "R = S / M, where S is the risk and M is the level of countermeasures applied.",
  "R = S + M, where S is the risk and M is the level of countermeasures applied.",
  "R = M / S, where S is the risk and M is the level of countermeasures applied."],
 ["R = S × M، حيث S الخطر و M مستوى الإجراءات المضادة المطبَّقة على النظام.",
  "R = S / M، حيث S الخطر و M مستوى الإجراءات المضادة المطبَّقة على النظام.",
  "R = S + M، حيث S الخطر و M مستوى الإجراءات المضادة المطبَّقة على النظام.",
  "R = M / S، حيث S الخطر و M مستوى الإجراءات المضادة المطبَّقة على النظام."],
 1,
 "الخطر المتبقي R = S / M: يقسم الخطر على مستوى الإجراءات المضادة. الاتجاه صحيح: كل ما زادت الإجراءات (M) قلّ الخطر المتبقي."),

("q7","countermeasure_level_M","Understand",
 "The chapter states that M covers the number of countermeasures and which other thing?",
 "يذكر الفصل أن M تشمل عدد الإجراءات المضادة وأي شيء آخر إلى جانبها؟",
 ["Their effectiveness, so M represents the number combined with how well they work.",
  "Their purchase cost, so M represents the number combined with the money they cost.",
  "Their vendor name, so M represents the number combined with who supplied each control.",
  "Their deployment year, so M represents the number combined with how recently deployed."],
 ["فعاليتها، فتمثّل M العدد مقترناً بمدى نجاح الإجراءات فعلياً في تخفيض الخطر.",
  "كلفتها الشرائية، فتمثّل M العدد مقترناً بالمبلغ المالي الذي كلّفته الإجراءات.",
  "اسم المورّد، فتمثّل M العدد مقترناً بالجهة التي زوّدت المؤسسة بكل ضابط منها.",
  "سنة النشر، فتمثّل M العدد مقترناً بمدى حداثة تطبيق الإجراءات في المؤسسة."],
 0,
 "الفصل صريح: M تشمل عدد الإجراءات وفعاليتها معاً. العدد وحده لا يصلح كمقام (يصبح صفراً عند غياب الإجراءات)، فالمقصود العدد مقترناً بالفعالية."),

("q8","risk_matrix_red_corner","Apply",
 "In the risk matrix, under what condition does a threat fall in the red (high-risk) cell?",
 "في مصفوفة الخطر، تحت أي شرط يقع التهديد في الخلية الحمراء عالية الخطر؟",
 ["When the consequences are high and the frequency of attempts is also high together.",
  "When the consequences are high even though the frequency of attempts stays low.",
  "When the frequency of attempts is high even though the consequences remain low.",
  "When the threat affects more than one hardware asset at exactly the same moment."],
 ["لمّا تكون العواقب عالية وتكرار المحاولات عالياً معاً في الوقت نفسه على المصفوفة.",
  "لمّا تكون العواقب عالية حتى لو بقي تكرار المحاولات واطياً في مصفوفة الخطر.",
  "لمّا يكون تكرار المحاولات عالياً حتى لو بقيت العواقب واطية في مصفوفة الخطر.",
  "لمّا يؤثر التهديد على أكثر من أصل مادي واحد في اللحظة ذاتها داخل المؤسسة."],
 0,
 "الأحمر لا يظهر إلا عند اجتماع العواقب العالية مع التكرار العالي معاً. الشكل 3.2 يبيّن أن الأحمر في خلية واحدة فقط: (تكرار عالٍ، عواقب عالية)."),

("q9","residual_matrix_red_corner","Apply",
 "In the residual-risk matrix, the red cell corresponds to which combination?",
 "في مصفوفة الخطر المتبقي، الخلية الحمراء تقابل أي اجتماع؟",
 ["High risk together with a low level of countermeasures being in place at the time.",
  "Low risk together with a low level of countermeasures being in place at the time.",
  "High risk together with a high level of countermeasures being in place at the time.",
  "Low risk together with a high level of countermeasures being in place at the time."],
 ["خطر عالٍ مع مستوى واطٍ من الإجراءات المضادة الموجودة في ذلك الوقت بعينه.",
  "خطر واطٍ مع مستوى واطٍ من الإجراءات المضادة الموجودة في ذلك الوقت بعينه.",
  "خطر عالٍ مع مستوى عالٍ من الإجراءات المضادة الموجودة في ذلك الوقت بعينه.",
  "خطر واطٍ مع مستوى عالٍ من الإجراءات المضادة الموجودة في ذلك الوقت بعينه."],
 0,
 "مصفوفة الخطر المتبقي محاورها (الخطر، الإجراءات المضادة) — لاحظ انعكاس محور الإجراءات. الأحمر = خطر عالٍ + إجراءات واطية، وهو الشكل 3.3."),

("q10","two_matrices_contrast","Analyze",
 "What is the key structural difference between the two matrices in the chapter?",
 "ما الفرق البنيوي الأساسي بين المصفوفتين في الفصل؟",
 ["The risk matrix pairs frequency with consequences, while the residual-risk matrix pairs risk with countermeasures.",
  "The risk matrix pairs risk with countermeasures, while the residual-risk matrix pairs frequency with consequences.",
  "The risk matrix applies only to software threats, while the residual-risk matrix applies only to physical threats in a building.",
  "The risk matrix is used before an audit, while the residual-risk matrix is used only after a formal certification review."],
 ["مصفوفة الخطر تجمع التكرار مع العواقب، بينما مصفوفة الخطر المتبقي تجمع الخطر مع الإجراءات المضادة.",
  "مصفوفة الخطر تجمع الخطر مع الإجراءات المضادة، بينما مصفوفة الخطر المتبقي تجمع التكرار مع العواقب.",
  "مصفوفة الخطر تُطبَّق فقط على تهديدات البرمجيات، بينما الثانية تُطبَّق فقط على التهديدات الفيزيائية في المبنى.",
  "مصفوفة الخطر تُستخدم قبل التدقيق، بينما مصفوفة الخطر المتبقي تُستخدم فقط بعد مراجعة شهادة رسمية معتمدة."],
 0,
 "مصفوفة الخطر: (تكرار F × عواقب K). مصفوفة الخطر المتبقي: (خطر S ÷ إجراءات M). المعادلة الأولى تُغذّي الثانية بمخرجها S، فهما مرحلتان لا بديلان."),

("q11","threat_groups_four","Remember",
 "Which set correctly lists the four main groups of threats in IT systems?",
 "أي مجموعة تذكر بشكل صحيح المجموعات الأربع الرئيسية للتهديدات في أنظمة تقنية المعلومات؟",
 ["Hardware related, Software related, Data related and Liveware related threats.",
  "Network related, Cloud related, Mobile related and Industrial related threats.",
  "Internal related, External related, Accidental related and Deliberate related threats.",
  "Physical related, Logical related, Human related and Environmental related threats."],
 ["تهديدات متعلقة بالمعدات، والبرمجيات، والبيانات، والعنصر البشري (Liveware).",
  "تهديدات متعلقة بالشبكة، والسحابة، والموبايل، والأنظمة الصناعية المتخصصة.",
  "تهديدات داخلية، وخارجية، وعرضية غير مقصودة، ومقصودة متعمّدة من الفاعل.",
  "تهديدات فيزيائية، ومنطقية، وبشرية، وبيئية محيطة بالمنشأة العاملة بها."],
 0,
 "المجموعات الأربع بحسب الفصل: Hardware · Software · Data · Liveware. البقية مجموعات مصنوعة ليست من تصنيف الفصل."),

("q12","hardware_threats_examples","Understand",
 "Which of the following is given as an example of a hardware-related threat?",
 "أي مما يلي يُعطى كمثال على تهديد متعلق بالمعدات (Hardware related)؟",
 ["Faults in the infrastructure that the computer depends on so as to work properly.",
  "Messages that trick an employee into revealing a password to a remote attacker.",
  "Programs that are wilfully malicious and spread from one machine to another one.",
  "Collecting accessible data from which confidential information can be deduced."],
 ["أعطال في البنية التحتية التي يعتمد عليها الحاسوب حتى يعمل بالشكل المطلوب.",
  "رسائل تخدع الموظف ليُفصح عن كلمة السر لمهاجم عن بعد يقف خلف العملية.",
  "برامج خبيثة بقصد الإضرار تنتشر من جهاز إلى جهاز آخر داخل الشبكة ذاتها.",
  "جمع بيانات متاحة يمكن منها استنتاج معلومات سرّية غير متاحة مباشرةً للطرف."],
 0,
 "تهديدات Hardware: بيئة ضارّة، كوارث طبيعية، هجوم فيزيائي كالسرقة، وأعطال البنية التحتية. الخيار الثاني = liveware، الثالث = software، الرابع = data."),

("q13","malware_definition","Remember",
 "Which of the following are listed as examples of malware in the chapter?",
 "أي مما يلي يُذكر كأمثلة على البرمجيات الخبيثة (malware) في الفصل؟",
 ["Viruses, worms, trojan horses and logic bombs that are wilfully malicious.",
  "Firewalls, antivirus programs and intrusion detection systems in the network.",
  "Backups, encryption keys and access-control lists protecting stored records.",
  "Deadbolts, cipher locks and access-control gates mounted on the building."],
 ["الفيروسات والديدان وأحصنة طروادة والقنابل المنطقية الخبيثة بقصد الإضرار.",
  "الجدران النارية وبرامج مكافحة الفيروسات وأنظمة كشف التسلل في الشبكة.",
  "النسخ الاحتياطية ومفاتيح التشفير وقوائم ضبط الوصول التي تحمي السجلات.",
  "المزاليج الميكانيكية والأقفال الرقمية وبوابات التحكم بالوصول في المبنى."],
 0,
 "الـ malware يشمل: الفيروسات، الديدان، أحصنة طروادة، القنابل المنطقية. الخيارات الأخرى تصف إجراءات مضادة أو تقنيات وصول، لا برمجيات خبيثة."),

("q14","data_threats_inference","Understand",
 "What is 'inference' as a data-related threat?",
 "ما هو 'الاستدلال' (inference) كتهديد متعلق بالبيانات؟",
 ["Collecting accessible data from which confidential information not directly accessible can be deduced.",
  "Copying a confidential file directly from a server that has no access controls enabled at all.",
  "Pretending to be another user in order to obtain their identity and credentials in the system.",
  "Deleting a database table by mistake while performing routine maintenance on the production server."],
 ["جمع بيانات متاحة يمكن منها استنتاج معلومات سرّية غير متاحة مباشرةً للطرف.",
  "نسخ ملف سرّي مباشرةً من خادم لا يمتلك أي ضوابط وصول مفعّلة إطلاقاً.",
  "انتحال شخصية مستخدم آخر للحصول على هويته وبيانات دخوله في النظام كله.",
  "حذف جدول في قاعدة البيانات بالخطأ أثناء صيانة روتينية على خادم الإنتاج."],
 0,
 "الـ inference ليست وصولاً مباشراً لبيانات سرّية، بل جمع بيانات متاحة واستنتاج المخفي منها. الخيار الثالث يصف masquerading، والباقي ليس inference."),

("q15","liveware_threats","Understand",
 "Which threats belong to the liveware-related group?",
 "أي التهديدات تنتمي إلى مجموعة التهديدات المتعلقة بالعنصر البشري (Liveware)؟",
 ["Social engineering, phishing, and computer-assisted fraud and forgery by people.",
  "Natural disasters such as storms and flooding damaging the physical equipment.",
  "Unauthorized modification or deletion of the installed application software.",
  "Inference of confidential information from otherwise accessible public data."],
 ["الهندسة الاجتماعية والتصيّد والاحتيال والتزوير بمساعدة الحاسوب من الأشخاص.",
  "الكوارث الطبيعية كالعواصف والفيضانات التي تُتلف المعدات المادية للمؤسسة.",
  "التعديل أو الحذف غير المصرّح به للبرمجيات التطبيقية المثبّتة في الأجهزة.",
  "استنتاج معلومات سرّية من بيانات متاحة أصلاً للعموم بلا وصول مباشر إليها."],
 0,
 "Liveware = خطأ/سلوك بشري عند المستخدمين: social engineering، phishing، احتيال وتزوير. الثاني = hardware، الثالث = software، الرابع = data."),

("q16","countermeasure_threat_matching","Apply",
 "Which countermeasure does the chapter match with the threat of attackers outside the system attacking through the Internet?",
 "أي إجراء مضاد يطابقه الفصل مع تهديد المهاجمين من خارج النظام عبر الإنترنت؟",
 ["Firewalls placed in the network to stop the attacker's traffic from reaching the target.",
  "Antivirus programs installed on each endpoint to stop malware from spreading locally.",
  "Regular backup copies taken so that damaged data and software can be restored later.",
  "Checking personnel and introducing suitable training for the authorised users."],
 ["جدران نارية في الشبكة تمنع مرور ترافيك المهاجم من الوصول إلى الهدف المحدد.",
  "برامج مضادة للفيروسات على كل جهاز لإيقاف انتشار البرمجيات الخبيثة محلياً.",
  "نسخ احتياطية دورية تُؤخذ حتى يمكن استرجاع البيانات والبرمجيات التالفة لاحقاً.",
  "فحص الأفراد وتدريب مناسب للمستخدمين المصرّح لهم العاملين داخل المؤسسة."],
 0,
 "الجدول يطابق: مهاجمون من الخارج عبر الإنترنت → Firewalls. Antivirus → malware. Backups → تعديل/حذف. فحص الأفراد → تهديدات الموظفين."),

("q17","countermeasure_personnel","Understand",
 "Which countermeasure does the chapter prescribe for threats coming from personnel and ordinary authorised users?",
 "أي إجراء مضاد يوصي به الفصل للتهديدات الآتية من الموظفين والمستخدمين المصرّح لهم العاديين؟",
 ["Checking the personnel and introducing suitable training programs for them.",
  "Placing all the equipment inside a secure room that is locked and monitored.",
  "Using strong encryption or an access-control list on every stored record.",
  "Taking regular backup copies of data and of the installed software as well."],
 ["فحص الأفراد وتقديم برامج تدريب مناسبة لهم للتعامل الصحيح مع الأمن.",
  "وضع كل المعدات داخل غرفة آمنة مقفلة وتحت مراقبة مستمرة على مدار الوقت.",
  "استخدام تشفير قوي أو قائمة ضبط وصول على كل سجل مخزَّن في النظام كله.",
  "أخذ نسخ احتياطية دورية من البيانات ومن البرمجيات المثبّتة على الأجهزة."],
 0,
 "لتهديدات الموظفين يوصي الفصل بفحص الأفراد (check personnel) وتقديم تدريب مناسب — علاج إداري/بشري لا تقني. البقية إجراءات لتهديدات أخرى."),

("q18","risk_management_vs_mitigation","Understand",
 "How does the chapter distinguish risk mitigation from risk management overall?",
 "كيف يميّز الفصل بين تخفيف الخطر (mitigation) وإدارته (management) بشكل عام؟",
 ["Risk management covers all evaluating and reducing activities, while mitigation is the part reducing risk to an acceptable level.",
  "Risk mitigation covers all evaluating and reducing activities, while risk management is only the part that transfers the risk to a third party by contract.",
  "Risk management applies only to hardware threats, while risk mitigation applies only to the software and data threats in the organisation.",
  "Risk mitigation is used before an incident happens, while risk management is used only after the damage has already occurred to the organisation."],
 ["إدارة الخطر تشمل كل أنشطة التقييم والتخفيض، أما التخفيف فهو الجزء الذي يوصل الخطر لمستوى مقبول.",
  "تخفيف الخطر يشمل كل أنشطة التقييم والتخفيض، أما إدارة الخطر فهي فقط الجزء الذي ينقل الخطر لطرف آخر بعقد.",
  "إدارة الخطر تُطبَّق فقط على تهديدات المعدات، أما تخفيف الخطر فيُطبَّق فقط على تهديدات البرمجيات والبيانات.",
  "تخفيف الخطر يُستخدم قبل وقوع الحادث، أما إدارة الخطر فتُستخدم فقط بعدما يقع الضرر فعلاً على المؤسسة."],
 0,
 "إدارة الخطر = المظلة (كل نشاط تقييم وتخفيض). التخفيف (mitigation) = الجزء الذي هدفه الوصول بالخطر إلى مستوى مقبول."),

("q19","mitigation_five_strategies","Remember",
 "Which set lists the five risk-mitigation strategies in the order given?",
 "أي مجموعة تذكر الاستراتيجيات الخمس لتخفيف الخطر بالترتيب الوارد؟",
 ["Avoidance, Reduction, Retention, Transfer and Sharing of the remaining risk.",
  "Avoidance, Retention, Reduction, Sharing and Transfer of the remaining risk.",
  "Reduction, Avoidance, Transfer, Retention and Sharing of the remaining risk.",
  "Sharing, Transfer, Retention, Reduction and Avoidance of the remaining risk."],
 ["التجنّب، والتخفيض، والاحتفاظ، والنقل، والتقاسم للخطر المتبقي بالترتيب.",
  "التجنّب، والاحتفاظ، والتخفيض، والتقاسم، والنقل للخطر المتبقي بالترتيب.",
  "التخفيض، والتجنّب، والنقل، والاحتفاظ، والتقاسم للخطر المتبقي بالترتيب.",
  "التقاسم، والنقل، والاحتفاظ، والتخفيض، والتجنّب للخطر المتبقي بالترتيب."],
 0,
 "الترتيب مهم: Avoidance → Reduction → Retention → Transfer → Sharing. الدكتورة ظلّلتها بالأصفر فهي قابلة للحفظ بالترتيب."),

("q20","strategy_scenario_outsourcing","Apply",
 "A company signs a contract with an outside firm so that the outside firm bears a specific risk. Which strategy is this?",
 "شركة توقّع عقداً مع جهة خارجية حتى تتحمّل تلك الجهة خطراً معيّناً. أي استراتيجية هذه؟",
 ["Risk transfer, because the risk is moved to another party through a contract.",
  "Risk sharing, because the risk is dealt with jointly by two or more parties.",
  "Risk retention, because a certain agreed amount of residual risk is allowed.",
  "Risk avoidance, because the target system is kept away from the given risk."],
 ["نقل الخطر (transfer)، لأن الخطر يُنقل إلى طرف آخر من خلال عقد مبرم.",
  "تقاسم الخطر (sharing)، لأن الخطر يُعالَج بالمشاركة بين طرفين أو أكثر.",
  "الاحتفاظ بالخطر (retention)، لأن قدراً متّفقاً من الخطر المتبقي يُقبل.",
  "تجنّب الخطر (avoidance)، لأن النظام المستهدف يُبعَد عن الخطر المحدد."],
 0,
 "النقل (transfer) = تخلّي عن الخطر لطرف آخر عبر عقد (مثل outsourcing). أما sharing = تقاسم، retention = قبول الخطر المتبقي، avoidance = إبعاد النظام."),

("q21","analysis_frameworks_five","Remember",
 "Which set lists the five well-known frameworks for systematic security analysis?",
 "أي مجموعة تذكر الأطر الخمسة المعروفة للتحليل المنهجي للأمن؟",
 ["COBIT, COSO, FAIR, ISO/IEC 27002 and OCTAVE as the recognised examples.",
  "COBIT, COSO, FAIR, ISO/IEC 27001 and PDCA as the recognised examples.",
  "NIST, ISO/IEC 27001, GDPR, HIPAA and COBIT as the recognised examples.",
  "FAIR, OCTAVE, NIST, PDCA and COSO as the recognised examples in the chapter."],
 ["كوبيت، وكوسو، وفير، وأيزو 27002، وأوكتيف كأمثلة معروفة في الفصل.",
  "كوبيت، وكوسو، وفير، وأيزو 27001، و PDCA كأمثلة معروفة في الفصل.",
  "نيست، وأيزو 27001، و GDPR، و HIPAA، وكوبيت كأمثلة معروفة في الفصل.",
  "فير، وأوكتيف، ونيست، و PDCA، وكوسو كأمثلة معروفة في الفصل الدراسي."],
 0,
 "الأطر الخمسة: COBIT · COSO · FAIR · ISO/IEC 27002 · OCTAVE. لاحظ أنها 27002 (قائمة الفحص) لا 27001، و PDCA عملية إدارة لا إطار تحليل منهجي."),

("q22","framework_fair_distinctive","Analyze",
 "Which framework is distinctive in offering a taxonomy, a naming standard and a model for calculating risk?",
 "أي إطار يتميّز بأنه يقدّم تصنيفاً ومعيار تسمية ونموذجاً لحساب الخطر؟",
 ["FAIR, the Factor Analysis of Information Risk used for naming and calculating risk.",
  "COBIT, the Control Objectives for Information and related Technology.",
  "COSO, the Committee of Sponsoring Organizations of the Treadway Commission.",
  "OCTAVE, the Operationally Critical Threat, Asset and Vulnerability Evaluation."],
 ["فير (FAIR)، تحليل عوامل خطر المعلومات، المستخدم للتسمية وحساب الخطر.",
  "كوبيت (COBIT)، أهداف الضبط لتقنية المعلومات والمرتبطة بها من مجالات.",
  "كوسو (COSO)، لجنة المنظمات الراعية التي تصف العمليات الداخلية للشركة.",
  "أوكتيف (OCTAVE)، تقييم التهديد الحرج تشغيلياً والأصول والثغرات في النظام."],
 0,
 "FAIR هو الوحيد الذي يقدّم الثلاثة: تصنيف (taxonomy) + معيار تسمية + نموذج حساب. COBIT = أهداف تدابير، COSO = عمليات داخلية، OCTAVE = عملية تحليل."),

("q23","framework_iso27002_checklist","Understand",
 "What does ISO/IEC 27002 present, according to the chapter?",
 "ماذا يقدّم معيار ISO/IEC 27002 بحسب الفصل؟",
 ["A checklist of things that must be considered in order to achieve a secure system.",
  "A detailed description of the internal processes a company must follow to lower risk.",
  "Objectives for the measures that can be used in order to manage the risk overall.",
  "A taxonomy of risk factors together with a standard for naming risk quantities."],
 ["قائمة تحقّق بالأمور الواجب مراعاتها للوصول إلى نظام آمن وفق المعيار.",
  "وصف تفصيلي للعمليات الداخلية التي يجب أن تتبعها الشركة لخفض الخطر.",
  "أهداف للتدابير التي يمكن استخدامها لإدارة الخطر على المستوى الكلي.",
  "تصنيف لعوامل الخطر مع معيار لتسمية الكميات المتعلقة بالخطر نفسه."],
 0,
 "ISO/IEC 27002 = checklist. الثاني = COSO، الثالث = COBIT، الرابع = FAIR. هذا التمييز هو الذي تُحفظ به الأطر الخمسة."),

("q24","iso27002_categories_count","Remember",
 "According to the chapter, how many categories does the latest version of ISO/IEC 27002 describe targets within?",
 "بحسب الفصل، كم فئة يصفها أحدث إصدار من ISO/IEC 27002؟",
 ["14 categories, and the standard is published jointly by ISO and the IEC together.",
  "4 categories, and the standard is published jointly by ISO and the IEC together.",
  "44 categories, and the standard is published jointly by ISO and the IEC together.",
  "93 categories, and the standard is published jointly by ISO and the IEC together."],
 ["14 فئة، والمعيار صادر بالاشتراك بين منظمة الأيزو واللجنة الكهروتقنية الدولية.",
  "4 فئات، والمعيار صادر بالاشتراك بين منظمة الأيزو واللجنة الكهروتقنية الدولية.",
  "44 فئة، والمعيار صادر بالاشتراك بين منظمة الأيزو واللجنة الكهروتقنية الدولية.",
  "93 فئة، والمعيار صادر بالاشتراك بين منظمة الأيزو واللجنة الكهروتقنية الدولية."],
 0,
 "المادة تقول 14 فئة (والدكتورة ظلّلت الرقم 14 بالأصفر). تنبيه دقيق: 14 هي هيكل نسخة 2013؛ نسخة 2022 أعادت التنظيم إلى 4 محاور/93 ضابطاً؛ لكن جواب الامتحان بحسب مادتها = 14. و44 = عدد معايير العائلة."),

("q25","iso27002_series_scope","Understand",
 "How many standards does the ISO/IEC 27002 series currently consist of, and what areas does it cover?",
 "من كم معيار تتكوّن سلسلة ISO/IEC 27002 حالياً، وما المجالات التي تغطّيها؟",
 ["44 complete or planned standards covering information security in general and in specific areas.",
  "14 complete or planned standards covering information security in general and in specific areas.",
  "4 complete or planned standards covering information security in general and in specific areas.",
  "93 complete or planned standards covering information security in general and in specific areas."],
 ["44 معياراً مكتملاً أو مخططاً تغطّي أمن المعلومات عموماً وفي مجالات محدّدة أيضاً.",
  "14 معياراً مكتملاً أو مخططاً تغطّي أمن المعلومات عموماً وفي مجالات محدّدة أيضاً.",
  "4 معايير مكتملة أو مخططة تغطّي أمن المعلومات عموماً وفي مجالات محدّدة أيضاً.",
  "93 معياراً مكتملاً أو مخططاً تغطّي أمن المعلومات عموماً وفي مجالات محدّدة أيضاً."],
 0,
 "السلسلة تتكوّن من 44 معياراً مكتملاً أو مخططاً، وتغطّي أمن المعلومات عموماً وفي مجالات كالتمويل والطاقة والأدلة الرقمية والحوسبة السحابية."),

("q26","octave_three_phases","Remember",
 "What are the three phases of OCTAVE, in order?",
 "ما المراحل الثلاث لمنهجية OCTAVE بالترتيب؟",
 ["Build asset-based threat profiles; identify infrastructure vulnerabilities; develop a security strategy and plans.",
  "Identify infrastructure vulnerabilities; build asset-based threat profiles; develop a security strategy and plans.",
  "Develop a security strategy and plans; build asset-based threat profiles; identify infrastructure vulnerabilities.",
  "Build asset-based threat profiles; develop a security strategy and plans; identify infrastructure vulnerabilities."],
 ["بناء ملفات تهديد مبنية على الأصول، ثم تحديد ثغرات البنية، ثم تطوير استراتيجية وخطط أمنية.",
  "تحديد ثغرات البنية، ثم بناء ملفات تهديد مبنية على الأصول، ثم تطوير استراتيجية وخطط أمنية.",
  "تطوير استراتيجية وخطط أمنية، ثم بناء ملفات تهديد مبنية على الأصول، ثم تحديد ثغرات البنية.",
  "بناء ملفات تهديد مبنية على الأصول، ثم تطوير استراتيجية وخطط أمنية، ثم تحديد ثغرات البنية."],
 0,
 "مراحل OCTAVE الثلاث بالترتيب: (1) asset-based threat profiles → (2) infrastructure vulnerabilities → (3) security strategy and plans. الدكتورة ظلّلتها بالأحمر."),

("q27","octave_origin_variants","Understand",
 "For which body was OCTAVE developed, and at which institution?",
 "لأي جهة طُوّرت منهجية OCTAVE، وفي أي مؤسسة أكاديمية؟",
 ["For the CERT organization, at Carnegie Mellon University in the United States of America.",
  "For the NIST agency, at the Massachusetts Institute of Technology in America.",
  "For the ISO organization, at the University of Geneva in Switzerland in Europe.",
  "For the IEC commission, at the Technical University of Denmark in Copenhagen."],
 ["لصالح منظمة CERT في جامعة كارنيجي ميلون في الولايات المتحدة الأمريكية.",
  "لصالح وكالة NIST في معهد ماساتشوستس للتقنية في الولايات المتحدة الأمريكية.",
  "لصالح منظمة ISO في جامعة جنيف في سويسرا الواقعة في القارة الأوروبية كلها.",
  "لصالح لجنة IEC في الجامعة التقنية في الدانمارك في مدينة كوبنهاغن نفسها."],
 0,
 "OCTAVE طُوّرت لصالح CERT في جامعة كارنيجي ميلون (CMU)، أمريكا. والاسم: Operationally Critical Threat, Asset and Vulnerability Evaluation."),

("q28","pdca_cycle","Remember",
 "What are the four characteristic phases of the PDCA process, in order?",
 "ما المراحل الأربع المميّزة لعملية PDCA بالترتيب؟",
 ["Plan, Do, Check and Act, forming a cycle that then repeats itself again.",
  "Plan, Check, Do and Act, forming a cycle that then repeats itself again.",
  "Prepare, Do, Check and Adjust, forming a cycle that then repeats itself.",
  "Plan, Do, Control and Audit, forming a cycle that then repeats itself."],
 ["التخطيط، ثم التنفيذ، ثم الفحص، ثم التصحيح، وتشكّل دورة تتكرر بعدها.",
  "التخطيط، ثم الفحص، ثم التنفيذ، ثم التصحيح، وتشكّل دورة تتكرر بعدها.",
  "التحضير، ثم التنفيذ، ثم الفحص، ثم التعديل، وتشكّل دورة تتكرر بعدها.",
  "التخطيط، ثم التنفيذ، ثم الضبط، ثم التدقيق، وتشكّل دورة تتكرر بعدها."],
 0,
 "PDCA = Plan · Do · Check · Act. والترتيب مهم لأنه دورة (cycle) لا خط مستقيم؛ تنتهي Act إما بتعديل أو ببدء دورة Plan جديدة."),

("q29","pdca_act_phase","Analyze",
 "What happens in the Act phase of the PDCA risk-management cycle?",
 "ماذا يحدث في مرحلة Act ضمن دورة PDCA لإدارة الخطر؟",
 ["The solution is adjusted so that the desired security level continues, or a new Plan phase is started.",
  "The threats are identified for the first time, the risks analysed and the countermeasures planned out.",
  "The countermeasures and other forms of risk management are implemented across the organisation.",
  "The implemented solution is monitored to check that the desired security level is actually maintained."],
 ["يُعدَّل الحل ليستمر بالمستوى المطلوب، أو يُقرَّر البدء بمرحلة Plan جديدة كاملة.",
  "تُحدَّد التهديدات لأول مرة، وتُحلَّل المخاطر، وتُخطَّط الإجراءات المضادة للمعالجة.",
  "تُنفَّذ الإجراءات المضادة وغيرها من أشكال إدارة الخطر على مستوى المؤسسة.",
  "يُراقَب الحل المنفَّذ للتأكد أن مستوى الأمن المطلوب محفوظ فعلاً على الأرض."],
 0,
 "Act = تعديل الحل ليستمر بالمستوى المطلوب، أو قرار ببدء دورة Plan جديدة. الثاني = Plan، الثالث = Do، الرابع = Check."),

("q30","authentication_inheritance_inherence","Apply",
 "A system verifies a user by scanning their fingerprint. Which authentication factor does this represent, and what is the correct standard term?",
 "نظام يتحقق من المستخدم عبر مسح بصمة إصبعه. أي عامل مصادقة يمثّل هذا، وما المصطلح الاصطلاحي الصحيح؟",
 ["Inherence, meaning something you are, which the booklet prints as 'Inheritance' among its four factors.",
  "Possession, meaning something you have, which the booklet prints as 'Possession' among its four factors.",
  "Knowledge, meaning something you know, which the booklet prints as 'Knowledge' among its four factors.",
  "Location, meaning somewhere you are, which the booklet prints as 'Location' among its four factors."],
 ["السمة الذاتية Inherence، أي شيء أنت عليه، والملزمة تكتبها Inheritance ضمن عواملها الأربعة.",
  "الحيازة Possession، أي شيء تملكه، والملزمة تكتبها Possession ضمن عواملها الأربعة.",
  "المعرفة Knowledge، أي شيء تعرفه، والملزمة تكتبها Knowledge ضمن عواملها الأربعة.",
  "الموقع Location، أي مكان أنت فيه، والملزمة تكتبها Location ضمن عواملها الأربعة."],
 0,
 "البصمة = شيء أنت عليه، أي السمة الذاتية. الملزمة تكتبه Inheritance، والمصطلح الاصطلاحي الصحيح هو Inherence. عواملها الأربعة: Knowledge · Possession · Inheritance · Location."),
]

# Balanced key pattern 8/8/7/7, interleaved (no runs)
TARGET = list("ABCD" * 7 + "AB")
assert Counter(TARGET) == {"A": 8, "B": 8, "C": 7, "D": 7}

questions = []
for idx, (qid, cid, bloom, qen, qar, oen, oar, ci, expl) in enumerate(ITEMS):
    want = LETTERS.index(TARGET[idx])
    def rot(lst):
        # new[want] must equal old[ci]  =>  new[j] = old[(j - want + ci) % 4]
        return [lst[(j - want + ci) % 4] for j in range(4)]
    ro, ra = rot(oen), rot(oar)
    questions.append({
        "id": qid, "concept_id": cid, "bloom_level": bloom,
        "question": qen, "question_ar": qar,
        "options": list(ro), "options_ar": ra, "options_en": list(ro),
        "answer": LETTERS[want], "correct": want, "explanation": expl,
    })
    # semantic guard: the rotated correct slot MUST still be the intended option
    assert questions[-1]["options"][want] == oen[ci], qid
    assert questions[-1]["options_ar"][want] == oar[ci], qid

doc = {
    "schema_version": 2, "subject_id": "01_Cyber_Security",
    "subject_title": "الأمن السيبراني", "semester": 1, "semester_label": "كورس أول",
    "quiz_id": "Quiz_02_Risk_Assessment",
    "topic": "Week 02: Cybersecurity Risks, Threats, Countermeasures & Risk Management",
    "instructor_ar": "أ.م.د. هدى لفتة مجيد",
    "instructor": "Asst. Prof. Dr. Huda Lafta Majeed",
    "subject": "01_Cyber_Security", "questions": questions,
}

os.makedirs(os.path.dirname(OUT), exist_ok=True)
with open(OUT, "w", encoding="utf-8") as f:
    json.dump(doc, f, ensure_ascii=False, indent=2)

print("WROTE:", OUT)
print("questions:", len(questions))
print("keys:", dict(Counter(q["answer"] for q in questions)))
prob = []
for q in questions:
    if re.search(r"\([^)]*\)", " ".join(q["options_en"])): prob.append((q["id"], "EN parenthetical"))
    for a in q["options_ar"]:
        if not re.search(r"[\u0600-\u06FF]", a): prob.append((q["id"], "AR missing"))
    for b in q["options_en"]:
        if re.search(r"[\u0600-\u06FF]", b): prob.append((q["id"], "EN has Arabic"))
print("issues:", prob if prob else "CLEAN")
