#!/usr/bin/env python3
"""
Master Studio Quiz Balancer & Psychometric Validator
----------------------------------------------------
Algorithmic optimizer for quiz banks generated by AI models.
Eliminates LLM positional bias (e.g. 22/25 in B) and checks option length balance.

Usage:
  python quiz_balancer.py <path_to_quiz.json>
  python quiz_balancer.py <path_to_quiz.json> --check
  python quiz_balancer.py <path_to_quiz.json> -o <output.json>
"""

import json
import random
import sys
from collections import Counter
from pathlib import Path


def analyze_quiz(quiz_data: dict) -> dict:
    """Calculates answer distribution and option length statistics."""
    questions = quiz_data.get("questions", [])
    total = len(questions)
    if total == 0:
        return {"total": 0, "distribution": {}, "length_disparities": []}

    answers = []
    disparities = []

    for i, q in enumerate(questions):
        ans = q.get("answer") or q.get("correct")
        opts = q.get("options", [])
        if isinstance(opts, dict):
            keys = list(opts.keys())
            vals = list(opts.values())
            ans_letter = ans if isinstance(ans, str) else (keys[ans] if isinstance(ans, int) and ans < len(keys) else "A")
            corr_idx = keys.index(ans_letter) if ans_letter in keys else 0
            opts_list = vals
        elif isinstance(opts, list):
            if isinstance(ans, str) and ans.upper() in ["A", "B", "C", "D"]:
                corr_idx = ["A", "B", "C", "D"].index(ans.upper())
                ans_letter = ans.upper()
            elif isinstance(ans, int) and 0 <= ans < len(opts):
                corr_idx = ans
                ans_letter = ["A", "B", "C", "D"][ans]
            else:
                corr_idx = 0
                ans_letter = "A"
            opts_list = opts
        else:
            continue

        answers.append(ans_letter)

        if corr_idx < len(opts_list):
            c_len = len(str(opts_list[corr_idx]))
            other_lens = [len(str(opts_list[j])) for j in range(len(opts_list)) if j != corr_idx]
            avg_other = sum(other_lens) / len(other_lens) if other_lens else 1
            ratio = c_len / avg_other if avg_other > 0 else 1.0
            if ratio > 1.35:
                disparities.append({
                    "question_idx": i + 1,
                    "id": q.get("id", f"q{i+1}"),
                    "correct_len": c_len,
                    "avg_distractor_len": round(avg_other, 1),
                    "ratio": round(ratio, 2)
                })

    counts = Counter(answers)
    dist = {k: {"count": v, "percentage": round(v / total * 100, 1)} for k, v in sorted(counts.items())}

    return {
        "total": total,
        "distribution": dist,
        "dominant_letter": counts.most_common(1)[0] if counts else ("None", 0),
        "length_disparities": disparities
    }


def balance_quiz(quiz_data: dict, seed: int = None) -> dict:
    """
    Algorithmatically re-assigns option order using a balanced target distribution
    so that A, B, C, D are represented approximately equally (~25% each).
    """
    if seed is not None:
        random.seed(seed)

    questions = quiz_data.get("questions", [])
    total = len(questions)
    if total == 0:
        return quiz_data

    # Generate perfectly balanced target letters: e.g. for 25 questions: [A, B, C, D, A, B, C, D, ...]
    letters = ["A", "B", "C", "D"]
    target_letters = [letters[i % 4] for i in range(total)]
    random.shuffle(target_letters)

    for i, q in enumerate(questions):
        target_ans = target_letters[i]
        target_idx = letters.index(target_ans)

        # Extract current options
        opts = q.get("options", [])
        opts_ar = q.get("options_ar")
        opts_en = q.get("options_en")
        curr_ans = q.get("answer") or q.get("correct")

        if isinstance(opts, dict):
            keys = list(opts.keys())
            vals = list(opts.values())
            curr_ans_letter = curr_ans if isinstance(curr_ans, str) else (keys[curr_ans] if isinstance(curr_ans, int) else "A")
            curr_corr_idx = keys.index(curr_ans_letter) if curr_ans_letter in keys else 0
            opts_list = vals
        elif isinstance(opts, list):
            if isinstance(curr_ans, str) and curr_ans.upper() in letters:
                curr_corr_idx = letters.index(curr_ans.upper())
            elif isinstance(curr_ans, int) and 0 <= curr_ans < len(opts):
                curr_corr_idx = curr_ans
            else:
                curr_corr_idx = 0
            opts_list = list(opts)
        else:
            continue

        if curr_corr_idx >= len(opts_list):
            curr_corr_idx = 0

        # Permute so that curr_corr_idx lands at target_idx
        num_opts = len(opts_list)
        if num_opts < 4:
            continue

        indices = list(range(num_opts))
        # Remove correct index from pool
        indices.remove(curr_corr_idx)
        # Randomize distractors
        random.shuffle(indices)
        # Insert correct index at target_idx
        indices.insert(target_idx, curr_corr_idx)

        # Apply permutation
        new_opts = [opts_list[idx] for idx in indices]
        q["options"] = new_opts
        q["answer"] = target_ans

        if isinstance(opts_ar, list) and len(opts_ar) == num_opts:
            q["options_ar"] = [opts_ar[idx] for idx in indices]

        if isinstance(opts_en, list) and len(opts_en) == num_opts:
            q["options_en"] = [opts_en[idx] for idx in indices]

    return quiz_data


def main():
    import argparse

    parser = argparse.ArgumentParser(description="Master Studio Quiz Balancer & Psychometric Validator")
    parser.add_argument("quiz_path", help="Path to quiz JSON file")
    parser.add_argument("-o", "--output", help="Output file path (defaults to overwriting input)")
    parser.add_argument("--check", action="store_true", help="Only check psychometric health without modifying")
    parser.add_argument("--seed", type=int, default=42, help="Random seed for deterministic balancing")

    args = parser.parse_args()
    path = Path(args.quiz_path)
    if not path.is_file():
        print(f"Error: File not found: {path}")
        sys.exit(1)

    with open(path, "r", encoding="utf-8") as f:
        quiz_data = json.load(f)

    stats_before = analyze_quiz(quiz_data)

    print("=" * 65)
    print(f"📊 QUIZ PSYCHOMETRIC AUDIT: {path.name}")
    print(f"   Topic: {quiz_data.get('topic', 'N/A')} ({stats_before['total']} Questions)")
    print("=" * 65)
    print("Answer Key Distribution (Current):")
    for k, v in stats_before["distribution"].items():
        bar = "█" * int(v["percentage"] / 4)
        print(f"  Option {k}: {v['count']:2d} ({v['percentage']:5.1f}%) {bar}")

    dom_letter, dom_count = stats_before["dominant_letter"]
    dom_pct = round(dom_count / stats_before["total"] * 100, 1) if stats_before["total"] > 0 else 0
    if dom_pct > 32.0:
        print(f"\n⚠️  CRITICAL BIAS DETECTED: Option {dom_letter} accounts for {dom_pct}% of answers!")
        print("   (Standard: no option should exceed 30% in a balanced exam).")

    disparities = stats_before["length_disparities"]
    if disparities:
        print(f"\n⚠️  LENGTH BIAS DETECTED: {len(disparities)}/{stats_before['total']} questions have tell-tale longest correct options:")
        for d in disparities[:5]:
            print(f"   - Q{d['question_idx']} ({d['id']}): Correct={d['correct_len']} chars vs Distractors={d['avg_distractor_len']} chars ({d['ratio']}x longer)")
        if len(disparities) > 5:
            print(f"   ... and {len(disparities) - 5} more questions.")

    if args.check:
        print("\n[Check mode only — no changes made]")
        return

    # Perform balancing
    balanced_data = balance_quiz(quiz_data, seed=args.seed)
    stats_after = analyze_quiz(balanced_data)

    print("\n" + "-" * 65)
    print("✅ ALGORITHMICALLY BALANCED DISTRIBUTION:")
    for k, v in stats_after["distribution"].items():
        bar = "█" * int(v["percentage"] / 4)
        print(f"  Option {k}: {v['count']:2d} ({v['percentage']:5.1f}%) {bar}")

    out_path = Path(args.output) if args.output else path
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(balanced_data, f, ensure_ascii=False, indent=2)

    print(f"\n💾 Saved balanced quiz to: {out_path}")
    print("=" * 65)


if __name__ == "__main__":
    main()
