#!/usr/bin/env python3
"""
Master Studio Quiz Balancer & Psychometric Validator
----------------------------------------------------
Algorithmic optimizer for quiz banks generated by AI models.
Eliminates LLM positional bias (e.g. 22/25 in B) and checks option length balance.

Usage:
  python quiz_balancer.py <path_to_quiz.json>
  python quiz_balancer.py <path_to_quiz.json> --check
  python quiz_balancer.py <path_to_quiz.json> -o <output.json>
"""

import json
import random
import sys
from collections import Counter
from pathlib import Path


SUBJECT_METADATA = {
    "01_Cyber_Security": {
        "title": "الأمن السيبراني",
        "instructor_ar": "أ.م.د. هدى لفتة مجيد",
        "semester": 1,
        "semester_label": "كورس أول",
    },
    "02_English_Language": {
        "title": "اللغة الإنجليزية",
        "instructor_ar": "أ.م.د. حيدر عكاب علوان",
        "semester": 1,
        "semester_label": "كورس أول",
    },
    "03_Data_Mining": {
        "title": "تنقيب البيانات",
        "instructor_ar": "أ.م.د. أحمد شاكر عبد الرضا",
        "semester": 1,
        "semester_label": "كورس أول",
    },
    "04_Advanced_Software_Eng": {
        "title": "هندسة البرمجيات المتقدمة",
        "instructor_ar": "أ.م.د. علي فاهم نعمة",
        "semester": 1,
        "semester_label": "كورس أول",
    },
    "05_Soft_Computing": {
        "title": "الحوسبة المرنة",
        "instructor_ar": "أ.د. عبد الهادي محمد ادخيل",
        "semester": 1,
        "semester_label": "كورس أول",
    },
    "06_Artificial_Intelligence": {
        "title": "الذكاء الاصطناعي",
        "instructor_ar": "أ.د. سيف علي السعيدي",
        "semester": 1,
        "semester_label": "كورس أول",
    },
}


def normalize_quiz_schema(quiz_data: dict, subject_id: str = None, quiz_id: str = None) -> dict:
    """
    Normalizes a quiz bank to Canonical Schema v2:
      - schema_version: 2
      - subject_id, subject_title, semester, semester_label, quiz_id, topic, instructor_ar
      - converts dictionary options to 4-item lists
      - guarantees answer ('A'-'D') and correct (0-3) synchronization
      - guarantees options_ar and options_en 4-item arrays
      - ensures id, concept_id, bloom_level, question, question_ar, explanation
    """
    if not isinstance(quiz_data, dict):
        return quiz_data

    letters = ["A", "B", "C", "D"]

    # 1. Resolve subject metadata
    subj_slug = subject_id or quiz_data.get("subject_id") or quiz_data.get("subject") or "00_STUDIO_HUB"
    meta = SUBJECT_METADATA.get(subj_slug, {})

    quiz_data["schema_version"] = 2
    quiz_data["subject_id"] = subj_slug
    quiz_data["subject"] = subj_slug  # Backward compatibility alias
    quiz_data["subject_title"] = quiz_data.get("subject_title") or meta.get("title") or subj_slug.replace("_", " ")

    raw_sem = quiz_data.get("semester")
    if raw_sem is not None:
        try:
            sem_int = int(raw_sem)
        except (ValueError, TypeError):
            sem_int = 1 if "Semester_1" in str(raw_sem) else 2
    else:
        sem_int = meta.get("semester", 1)
    quiz_data["semester"] = sem_int
    quiz_data["semester_label"] = quiz_data.get("semester_label") or meta.get("semester_label") or ("كورس أول" if sem_int == 1 else "كورس ثاني")

    q_slug = quiz_id or quiz_data.get("quiz_id") or (quiz_data.get("topic", "Quiz").replace(" ", "_"))
    quiz_data["quiz_id"] = q_slug
    quiz_data["topic"] = quiz_data.get("topic") or q_slug
    quiz_data["instructor_ar"] = quiz_data.get("instructor_ar") or meta.get("instructor_ar") or quiz_data.get("instructor", "")
    quiz_data["instructor"] = quiz_data.get("instructor") or quiz_data["instructor_ar"]

    # 2. Normalize questions
    questions = quiz_data.get("questions", [])
    for i, q in enumerate(questions):
        if not isinstance(q, dict):
            continue

        q["id"] = q.get("id") or f"q{i+1}"
        q["concept_id"] = q.get("concept_id") or f"concept_{i+1}"

        bloom = q.get("bloom_level")
        if bloom and isinstance(bloom, str):
            q["bloom_level"] = bloom.strip().capitalize()
        else:
            q["bloom_level"] = "Understand"

        # Question prompts (bilingual)
        q_en = q.get("question") or q.get("text_en") or q.get("text") or q.get("question_ar") or ""
        q_ar = q.get("question_ar") or q.get("text") or q.get("question") or ""
        q["question"] = q_en
        q["question_ar"] = q_ar

        # Options list conversion
        raw_opts = q.get("options")
        if isinstance(raw_opts, dict):
            opts_list = [str(raw_opts.get(l, "")) for l in letters]
        elif isinstance(raw_opts, list):
            opts_list = [str(item) for item in raw_opts]
        else:
            opts_list = ["", "", "", ""]
        while len(opts_list) < 4:
            opts_list.append("")
        opts_list = opts_list[:4]
        q["options"] = opts_list

        # Answer & Correct index
        ans = q.get("answer")
        corr = q.get("correct")
        if isinstance(ans, str) and ans.upper() in letters:
            corr_idx = letters.index(ans.upper())
        elif isinstance(corr, int) and 0 <= corr < 4:
            corr_idx = corr
        elif isinstance(ans, int) and 0 <= ans < 4:
            corr_idx = ans
        else:
            corr_idx = 0
        q["correct"] = corr_idx
        q["answer"] = letters[corr_idx]

        # Options AR / EN
        raw_opts_ar = q.get("options_ar")
        if isinstance(raw_opts_ar, dict):
            opts_ar = [str(raw_opts_ar.get(l, "")) for l in letters]
        elif isinstance(raw_opts_ar, list):
            opts_ar = [str(item) for item in raw_opts_ar]
        else:
            opts_ar = list(opts_list)
        while len(opts_ar) < 4:
            opts_ar.append("")
        q["options_ar"] = opts_ar[:4]

        raw_opts_en = q.get("options_en")
        if isinstance(raw_opts_en, dict):
            opts_en = [str(raw_opts_en.get(l, "")) for l in letters]
        elif isinstance(raw_opts_en, list):
            opts_en = [str(item) for item in raw_opts_en]
        else:
            opts_en = list(opts_list)
        while len(opts_en) < 4:
            opts_en.append("")
        q["options_en"] = opts_en[:4]

        q["explanation"] = q.get("explanation") or ""

    return quiz_data


def validate_schema_v2(quiz_data: dict) -> tuple[bool, list[str]]:
    """
    Validates that a quiz dictionary complies with Canonical Schema v2:
      - schema_version == 2
      - top-level keys: subject_id, subject_title, semester, semester_label, quiz_id, topic, instructor_ar, questions
      - questions is non-empty list of dicts
      - each question has: id, concept_id, bloom_level, question, question_ar,
        options (len 4), options_ar (len 4), options_en (len 4),
        answer in A-D, correct in 0-3, letters[correct] == answer, explanation
    """
    errors = []
    if not isinstance(quiz_data, dict):
        return False, ["Quiz data must be a JSON dictionary."]

    if quiz_data.get("schema_version") != 2:
        errors.append(f"Invalid or missing 'schema_version': expected 2, got {quiz_data.get('schema_version')!r}")

    top_keys = [
        ("subject_id", str),
        ("subject_title", str),
        ("semester", int),
        ("semester_label", str),
        ("quiz_id", str),
        ("topic", str),
        ("instructor_ar", str),
    ]
    for key, expected_type in top_keys:
        val = quiz_data.get(key)
        if val is None or not isinstance(val, expected_type) or (isinstance(val, str) and not val.strip()):
            errors.append(f"Missing or invalid required top-level property '{key}' (expected non-empty {expected_type.__name__}).")

    if quiz_data.get("semester") not in (1, 2):
        errors.append(f"Invalid 'semester': expected 1 or 2, got {quiz_data.get('semester')!r}")

    questions = quiz_data.get("questions")
    if not isinstance(questions, list) or len(questions) == 0:
        errors.append("Property 'questions' must be a non-empty list.")
        return False, errors

    letters = ["A", "B", "C", "D"]
    allowed_bloom = {"Remember", "Understand", "Apply", "Analyze", "Evaluate", "Create"}

    for i, q in enumerate(questions):
        qid = q.get("id") or f"q{i+1}"
        if not isinstance(q, dict):
            errors.append(f"Question {i+1} must be a dictionary.")
            continue

        for prop in ["id", "concept_id", "question", "question_ar", "explanation"]:
            val = q.get(prop)
            if not isinstance(val, str) or not val.strip():
                errors.append(f"Q{i+1} ({qid}): Missing or empty required property '{prop}'.")

        bloom = q.get("bloom_level")
        if not isinstance(bloom, str) or bloom not in allowed_bloom:
            errors.append(f"Q{i+1} ({qid}): Invalid bloom_level '{bloom}'. Expected one of {sorted(allowed_bloom)}.")

        for opt_key in ["options", "options_ar", "options_en"]:
            arr = q.get(opt_key)
            if not isinstance(arr, list) or len(arr) != 4:
                errors.append(f"Q{i+1} ({qid}): '{opt_key}' must be an array of exactly 4 strings.")
            else:
                for idx, opt_item in enumerate(arr):
                    if not isinstance(opt_item, str) or not opt_item.strip():
                        errors.append(f"Q{i+1} ({qid}): '{opt_key}[{idx}]' must be a non-empty string.")

        ans = q.get("answer")
        corr = q.get("correct")
        if ans not in letters:
            errors.append(f"Q{i+1} ({qid}): 'answer' must be one of {letters}, got {ans!r}.")
        if not isinstance(corr, int) or corr not in range(4):
            errors.append(f"Q{i+1} ({qid}): 'correct' must be an integer 0..3, got {corr!r}.")
        if ans in letters and isinstance(corr, int) and 0 <= corr < 4:
            if letters[corr] != ans:
                errors.append(f"Q{i+1} ({qid}): Mismatch between 'correct' ({corr} -> {letters[corr]}) and 'answer' ({ans}).")

    return len(errors) == 0, errors

def analyze_quiz(quiz_data: dict) -> dict:
    """Calculates answer distribution and option length statistics."""
    questions = quiz_data.get("questions", [])
    total = len(questions)
    if total == 0:
        return {"total": 0, "distribution": {}, "length_disparities": []}

    answers = []
    disparities = []

    for i, q in enumerate(questions):
        ans = q.get("answer") or q.get("correct")
        opts = q.get("options", [])
        if isinstance(opts, dict):
            keys = list(opts.keys())
            vals = list(opts.values())
            ans_letter = ans if isinstance(ans, str) else (keys[ans] if isinstance(ans, int) and ans < len(keys) else "A")
            corr_idx = keys.index(ans_letter) if ans_letter in keys else 0
            opts_list = vals
        elif isinstance(opts, list):
            if isinstance(ans, str) and ans.upper() in ["A", "B", "C", "D"]:
                corr_idx = ["A", "B", "C", "D"].index(ans.upper())
                ans_letter = ans.upper()
            elif isinstance(ans, int) and 0 <= ans < len(opts):
                corr_idx = ans
                ans_letter = ["A", "B", "C", "D"][ans]
            else:
                corr_idx = 0
                ans_letter = "A"
            opts_list = opts
        else:
            continue

        answers.append(ans_letter)

        if corr_idx < len(opts_list):
            c_len = len(str(opts_list[corr_idx]))
            other_lens = [len(str(opts_list[j])) for j in range(len(opts_list)) if j != corr_idx]
            avg_other = sum(other_lens) / len(other_lens) if other_lens else 1
            ratio = c_len / avg_other if avg_other > 0 else 1.0
            if ratio > 1.35:
                disparities.append({
                    "question_idx": i + 1,
                    "id": q.get("id", f"q{i+1}"),
                    "correct_len": c_len,
                    "avg_distractor_len": round(avg_other, 1),
                    "ratio": round(ratio, 2)
                })

    counts = Counter(answers)
    dist = {k: {"count": v, "percentage": round(v / total * 100, 1)} for k, v in sorted(counts.items())}

    return {
        "total": total,
        "distribution": dist,
        "dominant_letter": counts.most_common(1)[0] if counts else ("None", 0),
        "length_disparities": disparities
    }

import re


def clean_parenthetical_bloat(text: str) -> str:
    """
    Cleans clumsy parenthetical English echoes from Arabic options while
    preserving uppercase technical acronyms like (KDD), (API), (OTP).
    e.g. 'المعلومات (information)' -> 'المعلومات'
         'خوارزميات معقّدة (complex mathematical algorithms)' -> 'خوارزميات معقّدة'
    """
    if not isinstance(text, str):
        return text

    def replacer(match):
        inner = match.group(1).strip()
        if inner.isupper() and len(inner) <= 6:
            return f" ({inner})"
        return ""

    cleaned = re.sub(r'\s*\(([A-Za-z\s\-_/]+)\)', replacer, text)
    return re.sub(r'\s{2,}', ' ', cleaned).strip()


def balance_quiz(quiz_data: dict, seed: int = None, clean_bloat: bool = True) -> dict:
    """
    Algorithmatically re-assigns option order using a balanced target distribution
    so that A, B, C, D are represented approximately equally (~25% each).
    """
    if seed is not None:
        random.seed(seed)

    questions = quiz_data.get("questions", [])
    total = len(questions)
    if total == 0:
        return quiz_data

    # Generate perfectly balanced target letters: e.g. for 25 questions: [A, B, C, D, A, B, C, D, ...]
    letters = ["A", "B", "C", "D"]
    target_letters = [letters[i % 4] for i in range(total)]
    random.shuffle(target_letters)

    for i, q in enumerate(questions):
        target_ans = target_letters[i]
        target_idx = letters.index(target_ans)

        # Extract current options
        opts = q.get("options", [])
        opts_ar = q.get("options_ar")
        opts_en = q.get("options_en")
        curr_ans = q.get("answer") or q.get("correct")

        if isinstance(opts, dict):
            keys = list(opts.keys())
            vals = list(opts.values())
            curr_ans_letter = curr_ans if isinstance(curr_ans, str) else (keys[curr_ans] if isinstance(curr_ans, int) else "A")
            curr_corr_idx = keys.index(curr_ans_letter) if curr_ans_letter in keys else 0
            opts_list = vals
        elif isinstance(opts, list):
            if isinstance(curr_ans, str) and curr_ans.upper() in letters:
                curr_corr_idx = letters.index(curr_ans.upper())
            elif isinstance(curr_ans, int) and 0 <= curr_ans < len(opts):
                curr_corr_idx = curr_ans
            else:
                curr_corr_idx = 0
            opts_list = list(opts)
        else:
            continue

        if curr_corr_idx >= len(opts_list):
            curr_corr_idx = 0

        # Permute so that curr_corr_idx lands at target_idx
        num_opts = len(opts_list)
        if num_opts < 4:
            continue

        indices = list(range(num_opts))
        # Remove correct index from pool
        indices.remove(curr_corr_idx)
        # Randomize distractors
        random.shuffle(indices)
        # Insert correct index at target_idx
        indices.insert(target_idx, curr_corr_idx)

        # Apply permutation and clean parenthetical bloat if requested
        if clean_bloat:
            new_opts = [clean_parenthetical_bloat(opts_list[idx]) for idx in indices]
        else:
            new_opts = [opts_list[idx] for idx in indices]

        q["options"] = new_opts
        q["answer"] = target_ans
        q["correct"] = letters.index(target_ans)

        if isinstance(opts_ar, list) and len(opts_ar) == num_opts:
            if clean_bloat:
                q["options_ar"] = [clean_parenthetical_bloat(opts_ar[idx]) for idx in indices]
            else:
                q["options_ar"] = [opts_ar[idx] for idx in indices]

        if isinstance(opts_en, list) and len(opts_en) == num_opts:
            q["options_en"] = [opts_en[idx] for idx in indices]
    return quiz_data
def validate_strict_gate(quiz_data: dict, max_length_ratio: float = 1.30, max_letter_pct: float = 32.0):
    """
    Strict psychometric quality gate for AI-generated multiple-choice questions.
    Returns (is_valid: bool, errors: List[str]).

    Validates:
      1. Length parity: No correct answer may exceed 1.30x the average length of distractors.
      2. Positional balance: No single letter (A, B, C, D) may exceed 32% of total questions.
      3. Zero parenthetical bloat: No options may contain redundant English echoes like 'المعلومات (information)'.
      4. Schema completeness: concept_id, bloom_level, question_ar, options_ar / options_en.
    """
    errors = []
    questions = quiz_data.get("questions", [])
    total = len(questions)
    if total == 0:
        return False, ["Quiz contains zero questions."]

    # 1. Check length disparity
    stats = analyze_quiz(quiz_data)
    for disp in stats.get("length_disparities", []):
        if disp["ratio"] > max_length_ratio:
            errors.append(
                f"Q{disp['question_idx']} ({disp['id']}): Length disparity tell detected! "
                f"Correct option ({disp['correct_len']} chars) is {disp['ratio']}x longer than distractors ({disp['avg_distractor_len']} chars). "
                f"Distractors must be expanded to match."
            )

    # 2. Check positional bias
    if total >= 8:
        dom_letter, dom_count = stats.get("dominant_letter", ("None", 0))
        dom_pct = (dom_count / total) * 100.0 if total > 0 else 0
        if dom_pct > max_letter_pct:
            errors.append(
                f"Severe positional bias: Option {dom_letter} accounts for {dom_pct:.1f}% of answers ({dom_count}/{total}). "
                f"Maximum allowed is {max_letter_pct}%. Run balance_quiz to redistribute."
            )
    elif total >= 4:
        # For small quizzes (4-7 questions), ensure every letter A, B, C, D appears at least once
        # and no single letter appears more than 2 times
        for letter in ["A", "B", "C", "D"]:
            count = stats["distribution"].get(letter, {}).get("count", 0)
            if count == 0:
                errors.append(f"Small quiz bias: Option {letter} has 0 questions. Every letter (A, B, C, D) must appear at least once.")
            elif count > 2:
                errors.append(f"Small quiz bias: Option {letter} appears {count} times (max allowed is 2).")
    # 3. Check for parenthetical bloat in options
    for i, q in enumerate(questions):
        qid = q.get("id", f"q{i+1}")
        opts = q.get("options", [])
        opts_list = list(opts.values()) if isinstance(opts, dict) else (opts if isinstance(opts, list) else [])
        for opt in opts_list:
            matches = re.findall(r'[\u0600-\u06FF\s]+\s*\(([A-Za-z\s\-_/]+)\)', str(opt))
            for m in matches:
                if not (m.strip().isupper() and len(m.strip()) <= 6):
                    errors.append(
                        f"Q{i+1} ({qid}): Parenthetical translation bloat detected: '({m})'. "
                        f"Technical terms must be in clean English, or common terms in clean Arabic without brackets."
                    )

    # 4. Check schema completeness
    for i, q in enumerate(questions):
        qid = q.get("id", f"q{i+1}")
        if not q.get("concept_id"):
            errors.append(f"Q{i+1} ({qid}): Missing 'concept_id' tag.")
        if not q.get("bloom_level"):
            errors.append(f"Q{i+1} ({qid}): Missing 'bloom_level' tag.")
        if not q.get("question_ar"):
            errors.append(f"Q{i+1} ({qid}): Missing 'question_ar' translation.")

    is_valid = len(errors) == 0
    return is_valid, errors


def main():
    import argparse

    parser = argparse.ArgumentParser(description="Master Studio Quiz Balancer & Psychometric Validator")
    parser.add_argument("quiz_path", help="Path to quiz JSON file")
    parser.add_argument("-o", "--output", help="Output file path (defaults to overwriting input)")
    parser.add_argument("--check", action="store_true", help="Only check psychometric health without modifying")
    parser.add_argument("--schema", action="store_true", help="Validate canonical schema v2 compliance")
    parser.add_argument("--normalize", action="store_true", help="Normalize quiz to canonical schema v2 and save")
    parser.add_argument("--strict", action="store_true", help="Enforce strict psychometric gate (exits with code 1 on any violation)")
    parser.add_argument("--seed", type=int, default=42, help="Random seed for deterministic balancing")
    args = parser.parse_args()
    path = Path(args.quiz_path)
    if not path.is_file():
        print(f"Error: File not found: {path}")
        sys.exit(1)

    with open(path, "r", encoding="utf-8") as f:
        quiz_data = json.load(f)

    stats_before = analyze_quiz(quiz_data)

    print("=" * 65)
    print(f"📊 QUIZ PSYCHOMETRIC AUDIT: {path.name}")
    print(f"   Topic: {quiz_data.get('topic', 'N/A')} ({stats_before['total']} Questions)")
    print("=" * 65)
    print("Answer Key Distribution (Current):")
    for k, v in stats_before["distribution"].items():
        bar = "█" * int(v["percentage"] / 4)
        print(f"  Option {k}: {v['count']:2d} ({v['percentage']:5.1f}%) {bar}")

    dom_letter, dom_count = stats_before["dominant_letter"]
    dom_pct = round(dom_count / stats_before["total"] * 100, 1) if stats_before["total"] > 0 else 0
    if dom_pct > 32.0:
        print(f"\n⚠️  CRITICAL BIAS DETECTED: Option {dom_letter} accounts for {dom_pct}% of answers!")
        print("   (Standard: no option should exceed 30% in a balanced exam).")

    disparities = stats_before["length_disparities"]
    if disparities:
        print(f"\n⚠️  LENGTH BIAS DETECTED: {len(disparities)}/{stats_before['total']} questions have tell-tale longest correct options:")
        for d in disparities[:5]:
            print(f"   - Q{d['question_idx']} ({d['id']}): Correct={d['correct_len']} chars vs Distractors={d['avg_distractor_len']} chars ({d['ratio']}x longer)")
        if len(disparities) > 5:
            print(f"   ... and {len(disparities) - 5} more questions.")

    v2_valid, v2_errors = validate_schema_v2(quiz_data)
    if not v2_valid:
        print(f"\n⚠️  SCHEMA V2 WARNING: {len(v2_errors)} schema issues detected:")
        for err in v2_errors[:5]:
            print(f"   - {err}")
        if len(v2_errors) > 5:
            print(f"   ... and {len(v2_errors) - 5} more schema issues.")
    else:
        print("\n✅ SCHEMA V2: 100% Canonical Schema v2 Compliant.")

    if args.schema:
        if not v2_valid:
            print("\n❌ Schema v2 Validation Failed.")
            sys.exit(1)
        else:
            print("\n✅ Schema v2 Validation Passed.")
            if args.check:
                sys.exit(0)
    if args.strict:
        is_valid, errors = validate_strict_gate(quiz_data)
        if not is_valid:
            print("\n" + "!" * 65)
            print("❌ STRICT PSYCHOMETRIC GATE FAILED:")
            for err in errors:
                print(f"  * {err}")
            print("\nACTION REQUIRED: The agent MUST fix the flagged issues above")
            print("before delivering or committing this quiz bank.")
            print("!" * 65)
            sys.exit(1)
        else:
            print("\n✅ STRICT PSYCHOMETRIC GATE PASSED: 100% Psychometrically Compliant.")

    if args.check:
        print("\n[Check mode only — no changes made]")
        return

    # If normalize-only requested
    if args.normalize and not args.output:
        # Normalize and save directly without re-balancing
        normalized_data = normalize_quiz_schema(quiz_data, quiz_id=path.stem)
        out_path = path
        with open(out_path, "w", encoding="utf-8") as f:
            json.dump(normalized_data, f, ensure_ascii=False, indent=2)
        print(f"\n💾 Saved normalized schema v2 quiz to: {out_path}")
        print("=" * 65)
        return

    # Perform balancing with schema normalization
    quiz_data = normalize_quiz_schema(quiz_data, quiz_id=path.stem)

    # Perform balancing
    balanced_data = balance_quiz(quiz_data, seed=args.seed)
    stats_after = analyze_quiz(balanced_data)

    print("\n" + "-" * 65)
    print("✅ ALGORITHMICALLY BALANCED DISTRIBUTION:")
    for k, v in stats_after["distribution"].items():
        bar = "█" * int(v["percentage"] / 4)
        print(f"  Option {k}: {v['count']:2d} ({v['percentage']:5.1f}%) {bar}")

    out_path = Path(args.output) if args.output else path
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(balanced_data, f, ensure_ascii=False, indent=2)

    print(f"\n💾 Saved balanced quiz to: {out_path}")
    print("=" * 65)


if __name__ == "__main__":
    main()
